#!/bin/bash

function diskspace
{
	clear
	df -k
}

function whoseon
{
	clear
	who
}

function menuage
{
	clear
	cat ~/shell/$0
}

function menu
{
	clear
	echo -e "\n\n\n\n\t\t\t\t\t\t\t\tSys Admin Menu\n"
	echo -e "\t\t\t\t\t1. Display disk space"
	echo -e "\t\t\t\t\t2. Display logged on users"
	echo -e "\t\t\t\t\t3. Display memory usage"
	echo -e "\t\t\t\t\t0. Exit program\n\n"
	echo -en "\t\t\t\t\t\t\t\tEnter option:"
	read -n 1 option	
}

while [ 1 ]
do
menu
case $option in
0)
	break ;;
1)
	diskspace ;;
2)
	whoseon ;;
3)
	menuage ;;
*)
	clear
	echo "Sorry, wrong selection" ;;
esac
echo -en "\n\n\t\t\t Hit any key to continue"
read -n 1 line
done
clear
