#!/bin/bash
# using zenity to create a menu

temp=$(mktemp temp.XXXXXX)
temp2=$(mktemp temp2.XXXXXX)

function diskspace
{
	df -k > $temp
	zenity --text-info --title "Disk space" --filename=$temp --width 750 --height 500
}

function whoseon
{
	who > $temp
	zenity --text-info --title "Logged in users" --filename=$temp --width 500 --height 10
}

function memusage
{
	cat /proc/meminfo > $temp
	zenity --text-info --title "Memory usage" --filename=$temp --width 300 --height 500
}

while [ 1 ]
do
	zenity --width 700 --height 300 --list --radiolist --title "Sys Admin Menu" --column "Select" --column "Menu Item" FALSE "Display diskspace" FALSE "Display users" FALSE "Display Memory Usage" FALSE "Exit" > $temp2
	if [ $? -eq 1 ]
	then
		break
	fi
	selection=$(cat $temp2)
	case $selection in
	"Display diskspace")
		diskspace ;;
	"Display users")
		whoseon ;;
	"Display Memory Usage")
		memusage ;;
	Exit)
		break ;;
	*)
		zenity --info "Sorry, invalid selection"
	esac
done
rm -f $temp
rm -f $temp2
